version: '3'
services:
  app:
    container_name: "bot"
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        STAGE: dev
    ports:
      - "8888:8080"
    tty: true
    stdin_open: true